[package]
name = "rest_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
server = { path = "server" }
serde = "1.0.133"
serde_json = "1.0.75"
serde_derive = "1.0.133"